# Generated by Django 4.1.7 on 2023-02-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_price_products_price_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='num_stars',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
